# Group.create(name: "Business")
# Group.create(name: "Personal")
# Group.create(name: "Family")
# Group.create(name: "Friends")

# GroupContact.create(group_id: 2, contact_id: 1)
# GroupContact.create(group_id: 1, contact_id: 1)
# GroupContact.create(group_id: 3, contact_id: 1)
# GroupContact.create(group_id: 4, contact_id: 1)
# GroupContact.create(group_id: 1, contact_id: 2)
# GroupContact.create(group_id: 2, contact_id: 3)
# GroupContact.create(group_id: 4, contact_id: 3)
# GroupContact.create(group_id: 3, contact_id: 4)
# GroupContact.create(group_id: 1, contact_id: 5)
# GroupContact.create(group_id: 3, contact_id: 5)